# Screen dimensions
SCREEN_WIDTH = 128
SCREEN_HEIGHT = 128
MIN_X = -SCREEN_WIDTH / 2
MAX_X = -MIN_X
MIN_Y = -SCREEN_HEIGHT / 2
MAX_Y = -MIN_Y

# Audio channels
MENU_CHANNEL = 0
MENU_FIREWORK_CHANNEL = 1
PLAYER_SHOOT_CHANNEL = 0
PLAYER_HIT_CHANNEL = 1
ENEMY_ATTACK_CHANNEL = 2
ENEMY_HIT_CHANNEL = 2
MUSIC_CHANNEL = 3

# Debugging
SHOW_HITBOX = False
DISABLE_MUSIC = False
